### ISSUE TITLE
Quick question: does this support dynamically generated styles?

### ISSUE THREAD

**Issue by staxmanade** [UXtemple/babel-plugin-react-autoprefix#14]
Does this only work on JSX in-line styles or can it also work on dynamic styles applied inside of a render()?

If I wanted to have some conditional style based on react state/props and generate different `style={myCustomStyle}` dynamically, does this somehow get run on each render pass?

Thanks,

**Comment by staxmanade** [comment]
no reply

**Comment by dariocravero** [comment]
Sorry I totally missed your message @staxmanade. A bit too late to answer but still: it only works at compilation time, it will try to trace object definitions a bit but it will ultimately only apply to things it can guess at compilation time.
