### ISSUE TITLE
Plugin doesn't prefix `display: flex` properly

### ISSUE THREAD

**Issue by joshblack** [UXtemple/babel-plugin-react-autoprefix#2]
Tried the following in a demo app:

``` js
class App {
  render() {
    return <div style={{ display: 'flex' }}>hi</div>;
  }
}
```

When prefixing `{ display: 'flex' }` I expect the output to be

``` js
  { display: 'flex;display:-webkit-flex;display:-ms-flexbox' }
```

See: https://github.com/petehunt/jsxstyle/blob/master/lib/autoprefix.js#L81

But instead I get:

``` js
{ display: [3, 'flex'] }
```

**Comment by dariocravero** [comment]
Thanks :) It should be fixed with https://github.com/UXtemple/autoprefix/commit/2317a09637a13669bf53160301bef2570a8465a8. Would you double check?

**Comment by joshblack** [comment]
The array of values is correct now, but you have to combine them all together since React will join an array of values by a comma which won't be valid CSS. 

For example, `style={{ display: ['-webkit-flex', 'flex'] }}` will give you the CSS property `display: -webkit-flex,flex;` on the node.
