### ISSUE TITLE
Fails on unexpected value in `style` prop

### ISSUE THREAD

**Issue by harlanlewis** [UXtemple/babel-plugin-react-autoprefix#3]
Great plugin, just what'd I'd been looking for!

One issue - build fails when the value of `style` prop does not meet expectations, for example a string or object. There's a good argument that this is an acceptable failure (or at least an optional linter warning/error), however it can cause problems with other tools.

For example, the popular [FormatJS](http://formatjs.io/react/) uses the `style` prop to set how numbers should be displayed, eg `<FormattedNumber style='currency'>`. While they probably shouldn't be using standard HTML attributes as props like this, it unfortunately prevents using both at the same time.

**Comment by dariocravero** [comment]
Sorry for the delay and thanks @harlanlewis! #1 landed a few minutes after your message and covers that use case :) It's [tested here](https://github.com/UXtemple/babel-plugin-react-autoprefix/blob/master/__tests__/index-test.es6#L32-L37). Would you mind double checking it now? Thanks!

**Comment by harlanlewis** [comment]
Fixed! Thanks for the super-quick and very useful work!

**Comment by dariocravero** [comment]
Amazing! :D
