### ISSUE TITLE
Support nested styles declared outside of the styles attribute

### ISSUE THREAD

**Issue by ianobermiller** [UXtemple/babel-plugin-react-autoprefix#8]
For instance, it would be awesome if this was supported:

``` js
const style = {
  foo: {
    alignItems: "center",
    display: "flex",
    width: 100
  }
};
<div style={style.foo} />
```

Perhaps the plugin will need some sort of marker to tell it to autoprefix some things, e.g.

``` js
const style = {
  foo: prefix({
    alignItems: "center",
    display: "flex",
    width: 100
  })
};
<div style={style.foo} />
```

Or, if smart enough, even:

```
const style = prefix({
  foo: {
    alignItems: "center",
    display: "flex",
    width: 100
  }
});
<div style={style.foo} />
```

**Comment by dariocravero** [comment]
Thanks for bringing this up :).

The autoprefixer wouldn't really worry about what happens in `style` itself, I think it should look for the contents of the key `foo` in the object `style`.

I've [added a failing test](https://github.com/UXtemple/babel-plugin-react-autoprefix/commit/b0e5efa73baf3a539ab4353538fa9b933da6e9ab) for it and [opened a branch to fix it](https://github.com/UXtemple/babel-plugin-react-autoprefix/tree/styles-in-object-key).

The issue [starts here](https://github.com/UXtemple/babel-plugin-react-autoprefix/blob/styles-in-object-key/index.es6#L52) as the node isn't an `ObjectExpression` and is a `MemberExpression` instead; hence the plugin returning right away an the output being the same :/.

I'm not very familiar with `babel` internals and can't seem to find a way to get that `MemberExpression`'s value resolved, i.e. get object in `style.foo`. Hopefully @sebmck can shed some light on this :). I will try to keep on hacking away on it though.

**Comment by sebmck** [comment]
Change [this](https://github.com/UXtemple/babel-plugin-react-autoprefix/blob/master/index.es6#L84) line to:

``` javascript
prefixStyle(this.get('value.expression').resolve(true));
```

**Comment by dariocravero** [comment]
Wow that was fast :) Thanks @sebmck :D.
