### ISSUE TITLE
moz- and webkit-prefixed properties lack leading `-`

### ISSUE THREAD

**Issue by harlanlewis** [UXtemple/babel-plugin-react-autoprefix#9]
Version 0.2.2.

Expected: `-webkit-box-align: center; …`
Result: `webkit-box-align: center; …` (lacks leading `-`)

Screenshot attached with a few examples. Is this an issue with the underlying [autoprefix](https://github.com/uxtemple/autoprefix)? Happy to provide a pull request if pointed in the right direction.

chrome dev tools:
<img width="268" alt="screenshot-2015-08-03 15-31-16" src="https://cloud.githubusercontent.com/assets/51766/9049255/da80c01a-39f4-11e5-9e82-79abf8c74bcf.png">

related console errors (firefox dev edition, same displayed in chrome & safari):
<img width="946" alt="screenshot-2015-08-03 15-45-47" src="https://cloud.githubusercontent.com/assets/51766/9049429/b7884798-39f6-11e5-9341-db99a729660a.png">

**Comment by dariocravero** [comment]
Yes it is! I saw that earlier on today and forgot to submit an issue :/. Well spotted and thanks for bringing it up :).

Feel free to do so, essentially, any prefixed rule (i.e. anything that starts with a `-` [when camelcased](https://github.com/UXtemple/autoprefix/blob/master/index.es6#L13) should have the first character uppercased. So instead of `webkitBoxAlign` we would see a key named `WebkitBoxAlign` which is what react understands as a prefixed property.

**Comment by ianobermiller** [comment]
Keep in mind the one differing, IE, which of course uses lowercase `ms` prefix when converting to the JS version.

**Comment by dariocravero** [comment]
Yup, that's why every key starting with `-` should be converted.

**Comment by dariocravero** [comment]
@harlanlewis fixed by https://github.com/UXtemple/autoprefix/commit/e6a455767defed4092195954f9b8a8ce932e9349#diff-66f71097ef4e567d5a73386a128838f4R11 :) Would you mind retesting if everything is ok? Published in `autoprefix@0.1.3`. Thanks! :)

**Comment by ianobermiller** [comment]
I think you misunderstood my comment; `-ms-flex` should become `msFlex`, not `MsFlex`.

**Comment by dariocravero** [comment]
Oops, my bad. [Fixed](https://github.com/UXtemple/autoprefix/commit/b471a53aa2ecfa3e97b6e9a168b7666a75d04598#diff-872b799435cd333c1978450f1995541cR1)! Thanks for spotting it @ianobermiller :).

**Comment by harlanlewis** [comment]
Tested, fixed! Thanks again for the quick improvement!

**Comment by dariocravero** [comment]
More than welcome!
